# Generated by Django 4.2.15 on 2025-09-19 02:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("time_entry", "Time Entry"),
                            ("overtime", "Overtime"),
                            ("modification", "Time Modification"),
                            ("project", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requires_manager_approval", models.BooleanField(default=True)),
                ("requires_admin_approval", models.BooleanField(default=False)),
                (
                    "auto_approve_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Approval Workflow",
                "verbose_name_plural": "Approval Workflows",
            },
        ),
    ]
