# Generated by Django 4.2.15 on 2025-09-19 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalworkflow",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="approvalworkflow",
            unique_together={("organization", "approval_type")},
        ),
    ]
