# Generated by Django 4.2.15 on 2025-09-19 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_initial"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_reports", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["organization", "report_type"],
                name="reports_rep_organiz_bdc0af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["created_by"], name="reports_rep_created_61f2ca_idx"
            ),
        ),
    ]
