# Generated by Django 4.2.15 on 2025-09-19 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_initial"),
        ("time_tracking", "0001_initial"),
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheetperiod",
            name="payroll_processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_timesheet_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timemodificationrequest",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="timemodificationrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_modification_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timemodificationrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_modification_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timemodificationrequest",
            name="time_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modification_requests",
                to="time_tracking.timeentry",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_time_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="organizations.department",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="projects.task",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="breakentry",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="breakentry",
            name="time_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="break_entries",
                to="time_tracking.timeentry",
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetperiod",
            index=models.Index(
                fields=["organization", "start_date", "end_date"],
                name="time_tracki_organiz_1f4ec0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetperiod",
            index=models.Index(
                fields=["is_open", "is_locked"], name="time_tracki_is_open_9bf377_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timesheetperiod",
            unique_together={("organization", "start_date", "end_date")},
        ),
        migrations.AddIndex(
            model_name="timemodificationrequest",
            index=models.Index(
                fields=["time_entry"], name="time_tracki_time_en_880d83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timemodificationrequest",
            index=models.Index(
                fields=["requested_by"], name="time_tracki_request_725c9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timemodificationrequest",
            index=models.Index(fields=["status"], name="time_tracki_status_ee1750_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["user", "date"], name="time_tracki_user_id_60c1d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["project", "date"], name="time_tracki_project_57328d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["task", "date"], name="time_tracki_task_id_9c2402_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["organization", "date"], name="time_tracki_organiz_f43497_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["status"], name="time_tracki_status_659a03_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["is_billable"], name="time_tracki_is_bill_b6159d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeentry",
            unique_together={("user", "date", "clock_in")},
        ),
        migrations.AddIndex(
            model_name="breakentry",
            index=models.Index(
                fields=["time_entry", "start_time"],
                name="time_tracki_time_en_00f94c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="breakentry",
            index=models.Index(
                fields=["break_type"], name="time_tracki_break_t_31a877_idx"
            ),
        ),
    ]
