# Generated by Django 4.2.15 on 2025-09-19 02:07

import apps.common.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("cost_center", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
            bases=(models.Model, apps.common.models.StatusChoicesMixin),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug can only contain lowercase letters, numbers, and hyphens.",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="United States", max_length=100)),
                (
                    "timezone",
                    models.CharField(default="America/New_York", max_length=50),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("date_format", models.CharField(default="MM/dd/yyyy", max_length=20)),
                ("time_format", models.CharField(default="12", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=50,
                    ),
                ),
                ("max_users", models.PositiveIntegerField(default=10)),
                (
                    "subscription_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
            bases=(models.Model, apps.common.models.StatusChoicesMixin),
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("can_invite_users", models.BooleanField(default=False)),
                ("can_manage_projects", models.BooleanField(default=False)),
                ("can_manage_teams", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=True)),
                ("can_manage_settings", models.BooleanField(default=False)),
                ("can_manage_billing", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Organization Member",
                "verbose_name_plural": "Organization Members",
            },
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("work_hours_per_day", models.PositiveIntegerField(default=8)),
                ("work_days_per_week", models.PositiveIntegerField(default=5)),
                ("overtime_threshold_daily", models.PositiveIntegerField(default=8)),
                ("overtime_threshold_weekly", models.PositiveIntegerField(default=40)),
                ("break_duration_minutes", models.PositiveIntegerField(default=15)),
                ("lunch_duration_minutes", models.PositiveIntegerField(default=60)),
                ("break_after_hours", models.PositiveIntegerField(default=4)),
                ("lunch_after_hours", models.PositiveIntegerField(default=6)),
                ("allow_manual_time_entry", models.BooleanField(default=True)),
                ("require_project_time_allocation", models.BooleanField(default=True)),
                ("allow_future_time_entries", models.BooleanField(default=False)),
                ("max_daily_hours", models.PositiveIntegerField(default=12)),
                ("require_time_approval", models.BooleanField(default=True)),
                ("auto_approve_regular_hours", models.BooleanField(default=False)),
                ("require_overtime_approval", models.BooleanField(default=True)),
                ("enable_compliance_monitoring", models.BooleanField(default=True)),
                (
                    "overtime_rate_multiplier",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
                ),
                (
                    "night_shift_differential",
                    models.DecimalField(decimal_places=2, default=0.1, max_digits=4),
                ),
                ("send_overtime_alerts", models.BooleanField(default=True)),
                ("send_break_reminders", models.BooleanField(default=True)),
                ("alert_manager_on_violations", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Organization Settings",
                "verbose_name_plural": "Organization Settings",
            },
        ),
    ]
