# Generated by Django 4.2.15 on 2025-09-19 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("time_tracking", "0001_initial"),
        ("organizations", "0001_initial"),
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancealert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compliancealert",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="compliancealert",
            name="time_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_alerts",
                to="time_tracking.timeentry",
            ),
        ),
        migrations.AddField(
            model_name="compliancealert",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="compliancealert",
            index=models.Index(
                fields=["user", "alert_type"], name="compliance__user_id_90e5cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancealert",
            index=models.Index(
                fields=["severity", "is_resolved"],
                name="compliance__severit_bfa75b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancealert",
            index=models.Index(
                fields=["created_at"], name="compliance__created_4811e7_idx"
            ),
        ),
    ]
